server:
  port: 80 #指定启动端口号
system:
  name: 宁寿堂健康管理系统
  logo: /common/images/ningshoutang1.png
  version: 1.0.1
  sessionTimeout: 3600 #session过期时间 单位秒
  UploadPath: d:/sweet/
  domain: http://zhq.ngrock.buyerhou.top



# Mysql数据库
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://47.106.180.72:3306/ningshoutang?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
    username: root
    password: zhijian789
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
