
# Mysql数据库
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://47.106.180.72:3306/report?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
    username: root
    password: zhijian789
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
