server:
  port: 80 #指定启动端口号
system:
  name: 康华国医馆
  logo:
  version: 1.0.0
  sessionTimeout: 3600 #session过期时间 单位秒
  UploadPath: d:/sweet/
  domain: http://ning.51ehealth.com.cn



# Mysql数据库
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://47.106.180.72:3306/kanghua?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
    username: root
    password: zhijian789
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
